# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-06 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='package',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('javascript_sdk', 0), ('ios_sdk', 1), ('android_sdk', 2)], null=True),
        ),
    ]
