# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-06 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_auto_20200806_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[('javascript_sdk', 0), ('ios_sdk', 1), ('android_sdk', 2)], default=1),
            preserve_default=False,
        ),
    ]
