version: '2'

services:  

  postgres:
    image: 'postgres:9.6'
    environment:
     POSTGRES_USER: 'licenses'
     POSTGRES_PASSWORD: 'licenses'
     POSTGRES_DB: 'licenses'

  license-server:
    build:
      context: ./license_portal
    links:
      - postgres
    volumes:
      - ./license_portal:/app

  license-server:
    build:
      context: ./license_portal
    links:
      - postgres
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./license_portal:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres