version: '2'

services:  

  postgres:
    image: 'postgres:9.6'
    environment:
     POSTGRES_USER: 'licenses'
     POSTGRES_PASSWORD: 'licenses'
     POSTGRES_DB: 'licenses'

  license-api:
    build:
      context: ./license_portal/api
    links:
      - postgres
    volumes:
      - ./license_portal/api:/appi
    command: python manage.py runserver 0.0.0.0:8081
    volumes:
      - ./license_portal/api:/appi
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  license-server:
    build:
      context: ./license_portal
    links:
      - postgres
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./license_portal:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres