# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-10 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_auto_20200806_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'production'), (1, 'evaluation')]),
        ),
        migrations.AlterField(
            model_name='license',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(0, 'javascript_sdk'), (1, 'ios_sdk'), (2, 'android_sdk')]),
        ),
    ]
